/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CoordinatesDTO } from '../models';
// @ts-ignore
import type { DragonCaveDTO } from '../models';
// @ts-ignore
import type { DragonHeadDTO } from '../models';
// @ts-ignore
import type { LocationDTO } from '../models';
// @ts-ignore
import type { PersonDTO } from '../models';
/**
 * CreateApi - axios parameter creator
 */
export const CreateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Создаёт пещеру и возвращает исходный DTO.
         * @summary Создать пещеру
         * @param {DragonCaveDTO} dragonCaveDTO Пещера дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCave: async (dragonCaveDTO: DragonCaveDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dragonCaveDTO' is not null or undefined
            assertParamExists('createCave', 'dragonCaveDTO', dragonCaveDTO)
            const localVarPath = `/createCave`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dragonCaveDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Создаёт координаты и возвращает исходный DTO.
         * @summary Создать координаты
         * @param {CoordinatesDTO} coordinatesDTO Координаты
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCoordinates: async (coordinatesDTO: CoordinatesDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'coordinatesDTO' is not null or undefined
            assertParamExists('createCoordinates', 'coordinatesDTO', coordinatesDTO)
            const localVarPath = `/createCoordinates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(coordinatesDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Создаёт голову дракона и возвращает исходный DTO.
         * @summary Создать голову дракона
         * @param {DragonHeadDTO} dragonHeadDTO Голова дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHead: async (dragonHeadDTO: DragonHeadDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dragonHeadDTO' is not null or undefined
            assertParamExists('createHead', 'dragonHeadDTO', dragonHeadDTO)
            const localVarPath = `/createHead`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dragonHeadDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Создаёт локацию и возвращает исходный DTO.
         * @summary Создать локацию
         * @param {LocationDTO} locationDTO Локация
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLocation: async (locationDTO: LocationDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'locationDTO' is not null or undefined
            assertParamExists('createLocation', 'locationDTO', locationDTO)
            const localVarPath = `/createLocation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(locationDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Создаёт персонажа. Если указана локация по id — будет привязана к персонажу.
         * @summary Создать персонажа
         * @param {PersonDTO} personDTO Персонаж
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPerson: async (personDTO: PersonDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'personDTO' is not null or undefined
            assertParamExists('createPerson', 'personDTO', personDTO)
            const localVarPath = `/createPerson`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(personDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CreateApi - functional programming interface
 */
export const CreateApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CreateApiAxiosParamCreator(configuration)
    return {
        /**
         * Создаёт пещеру и возвращает исходный DTO.
         * @summary Создать пещеру
         * @param {DragonCaveDTO} dragonCaveDTO Пещера дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCave(dragonCaveDTO: DragonCaveDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DragonCaveDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCave(dragonCaveDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CreateApi.createCave']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Создаёт координаты и возвращает исходный DTO.
         * @summary Создать координаты
         * @param {CoordinatesDTO} coordinatesDTO Координаты
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCoordinates(coordinatesDTO: CoordinatesDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoordinatesDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCoordinates(coordinatesDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CreateApi.createCoordinates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Создаёт голову дракона и возвращает исходный DTO.
         * @summary Создать голову дракона
         * @param {DragonHeadDTO} dragonHeadDTO Голова дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createHead(dragonHeadDTO: DragonHeadDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DragonHeadDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createHead(dragonHeadDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CreateApi.createHead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Создаёт локацию и возвращает исходный DTO.
         * @summary Создать локацию
         * @param {LocationDTO} locationDTO Локация
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createLocation(locationDTO: LocationDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LocationDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createLocation(locationDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CreateApi.createLocation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Создаёт персонажа. Если указана локация по id — будет привязана к персонажу.
         * @summary Создать персонажа
         * @param {PersonDTO} personDTO Персонаж
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPerson(personDTO: PersonDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PersonDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPerson(personDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CreateApi.createPerson']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CreateApi - factory interface
 */
export const CreateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CreateApiFp(configuration)
    return {
        /**
         * Создаёт пещеру и возвращает исходный DTO.
         * @summary Создать пещеру
         * @param {DragonCaveDTO} dragonCaveDTO Пещера дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCave(dragonCaveDTO: DragonCaveDTO, options?: RawAxiosRequestConfig): AxiosPromise<DragonCaveDTO> {
            return localVarFp.createCave(dragonCaveDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Создаёт координаты и возвращает исходный DTO.
         * @summary Создать координаты
         * @param {CoordinatesDTO} coordinatesDTO Координаты
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCoordinates(coordinatesDTO: CoordinatesDTO, options?: RawAxiosRequestConfig): AxiosPromise<CoordinatesDTO> {
            return localVarFp.createCoordinates(coordinatesDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Создаёт голову дракона и возвращает исходный DTO.
         * @summary Создать голову дракона
         * @param {DragonHeadDTO} dragonHeadDTO Голова дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHead(dragonHeadDTO: DragonHeadDTO, options?: RawAxiosRequestConfig): AxiosPromise<DragonHeadDTO> {
            return localVarFp.createHead(dragonHeadDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Создаёт локацию и возвращает исходный DTO.
         * @summary Создать локацию
         * @param {LocationDTO} locationDTO Локация
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLocation(locationDTO: LocationDTO, options?: RawAxiosRequestConfig): AxiosPromise<LocationDTO> {
            return localVarFp.createLocation(locationDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Создаёт персонажа. Если указана локация по id — будет привязана к персонажу.
         * @summary Создать персонажа
         * @param {PersonDTO} personDTO Персонаж
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPerson(personDTO: PersonDTO, options?: RawAxiosRequestConfig): AxiosPromise<PersonDTO> {
            return localVarFp.createPerson(personDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CreateApi - object-oriented interface
 */
export class CreateApi extends BaseAPI {
    /**
     * Создаёт пещеру и возвращает исходный DTO.
     * @summary Создать пещеру
     * @param {DragonCaveDTO} dragonCaveDTO Пещера дракона
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCave(dragonCaveDTO: DragonCaveDTO, options?: RawAxiosRequestConfig) {
        return CreateApiFp(this.configuration).createCave(dragonCaveDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Создаёт координаты и возвращает исходный DTO.
     * @summary Создать координаты
     * @param {CoordinatesDTO} coordinatesDTO Координаты
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCoordinates(coordinatesDTO: CoordinatesDTO, options?: RawAxiosRequestConfig) {
        return CreateApiFp(this.configuration).createCoordinates(coordinatesDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Создаёт голову дракона и возвращает исходный DTO.
     * @summary Создать голову дракона
     * @param {DragonHeadDTO} dragonHeadDTO Голова дракона
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createHead(dragonHeadDTO: DragonHeadDTO, options?: RawAxiosRequestConfig) {
        return CreateApiFp(this.configuration).createHead(dragonHeadDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Создаёт локацию и возвращает исходный DTO.
     * @summary Создать локацию
     * @param {LocationDTO} locationDTO Локация
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createLocation(locationDTO: LocationDTO, options?: RawAxiosRequestConfig) {
        return CreateApiFp(this.configuration).createLocation(locationDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Создаёт персонажа. Если указана локация по id — будет привязана к персонажу.
     * @summary Создать персонажа
     * @param {PersonDTO} personDTO Персонаж
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPerson(personDTO: PersonDTO, options?: RawAxiosRequestConfig) {
        return CreateApiFp(this.configuration).createPerson(personDTO, options).then((request) => request(this.axios, this.basePath));
    }
}

