/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CoordinatesDTO } from '../models';
// @ts-ignore
import type { DragonCaveDTO } from '../models';
// @ts-ignore
import type { DragonHeadDTO } from '../models';
// @ts-ignore
import type { LocationDTO } from '../models';
// @ts-ignore
import type { PersonDTO } from '../models';
/**
 * GetApi - axios parameter creator
 */
export const GetApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Получить пещеры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCaves: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getCaves`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить координаты
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoordinates: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getCoordinates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить головы драконов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeads: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getHead`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить локации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLocations: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getLocation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить персонажей
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPersons: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getPerson`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GetApi - functional programming interface
 */
export const GetApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GetApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Получить пещеры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCaves(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DragonCaveDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCaves(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetApi.getCaves']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить координаты
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCoordinates(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CoordinatesDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCoordinates(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetApi.getCoordinates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить головы драконов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHeads(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DragonHeadDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHeads(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetApi.getHeads']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить локации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLocations(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LocationDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLocations(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetApi.getLocations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить персонажей
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPersons(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PersonDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPersons(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GetApi.getPersons']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GetApi - factory interface
 */
export const GetApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GetApiFp(configuration)
    return {
        /**
         * 
         * @summary Получить пещеры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCaves(options?: RawAxiosRequestConfig): AxiosPromise<Array<DragonCaveDTO>> {
            return localVarFp.getCaves(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить координаты
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCoordinates(options?: RawAxiosRequestConfig): AxiosPromise<Array<CoordinatesDTO>> {
            return localVarFp.getCoordinates(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить головы драконов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeads(options?: RawAxiosRequestConfig): AxiosPromise<Array<DragonHeadDTO>> {
            return localVarFp.getHeads(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить локации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLocations(options?: RawAxiosRequestConfig): AxiosPromise<Array<LocationDTO>> {
            return localVarFp.getLocations(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить персонажей
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPersons(options?: RawAxiosRequestConfig): AxiosPromise<Array<PersonDTO>> {
            return localVarFp.getPersons(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GetApi - object-oriented interface
 */
export class GetApi extends BaseAPI {
    /**
     * 
     * @summary Получить пещеры
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCaves(options?: RawAxiosRequestConfig) {
        return GetApiFp(this.configuration).getCaves(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить координаты
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCoordinates(options?: RawAxiosRequestConfig) {
        return GetApiFp(this.configuration).getCoordinates(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить головы драконов
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getHeads(options?: RawAxiosRequestConfig) {
        return GetApiFp(this.configuration).getHeads(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить локации
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLocations(options?: RawAxiosRequestConfig) {
        return GetApiFp(this.configuration).getLocations(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить персонажей
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPersons(options?: RawAxiosRequestConfig) {
        return GetApiFp(this.configuration).getPersons(options).then((request) => request(this.axios, this.basePath));
    }
}

