# Билдим React
FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

# Отдаём статику через Nginx
FROM nginx:1.27-alpine
# Копируем конфиг из deploy (теперь он внутри build context, т.к. context='.')
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
