# Сборка jar
FROM gradle:8.8-jdk21-alpine AS build
WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/home/gradle/.gradle ./gradlew --no-daemon clean bootJar

# Тонкий рантайм
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
ENV JAVA_OPTS=""
EXPOSE 8080
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar app.jar"]
