/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AuthRespForm } from '../models';
// @ts-ignore
import type { SignInRequest } from '../models';
// @ts-ignore
import type { SignUpRequest } from '../models';
/**
 * AuthenticationApi - axios parameter creator
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Аутентифицирует пользователя и возвращает форму ответа (обычно с JWT).
         * @summary Вход пользователя
         * @param {SignInRequest} signInRequest Данные для входа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSignIn: async (signInRequest: SignInRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signInRequest' is not null or undefined
            assertParamExists('authSignIn', 'signInRequest', signInRequest)
            const localVarPath = `/auth/sign-in`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signInRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Создаёт нового пользователя и возвращает форму ответа с токеном/данными.
         * @summary Регистрация пользователя
         * @param {SignUpRequest} signUpRequest Данные для регистрации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSignUp: async (signUpRequest: SignUpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signUpRequest' is not null or undefined
            assertParamExists('authSignUp', 'signUpRequest', signUpRequest)
            const localVarPath = `/auth/sign-up`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signUpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * Аутентифицирует пользователя и возвращает форму ответа (обычно с JWT).
         * @summary Вход пользователя
         * @param {SignInRequest} signInRequest Данные для входа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSignIn(signInRequest: SignInRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthRespForm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authSignIn(signInRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.authSignIn']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Создаёт нового пользователя и возвращает форму ответа с токеном/данными.
         * @summary Регистрация пользователя
         * @param {SignUpRequest} signUpRequest Данные для регистрации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSignUp(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthRespForm>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authSignUp(signUpRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.authSignUp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * Аутентифицирует пользователя и возвращает форму ответа (обычно с JWT).
         * @summary Вход пользователя
         * @param {SignInRequest} signInRequest Данные для входа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSignIn(signInRequest: SignInRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthRespForm> {
            return localVarFp.authSignIn(signInRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Создаёт нового пользователя и возвращает форму ответа с токеном/данными.
         * @summary Регистрация пользователя
         * @param {SignUpRequest} signUpRequest Данные для регистрации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSignUp(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthRespForm> {
            return localVarFp.authSignUp(signUpRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * Аутентифицирует пользователя и возвращает форму ответа (обычно с JWT).
     * @summary Вход пользователя
     * @param {SignInRequest} signInRequest Данные для входа
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authSignIn(signInRequest: SignInRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).authSignIn(signInRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Создаёт нового пользователя и возвращает форму ответа с токеном/данными.
     * @summary Регистрация пользователя
     * @param {SignUpRequest} signUpRequest Данные для регистрации
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authSignUp(signUpRequest: SignUpRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).authSignUp(signUpRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

