/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * DeleteApi - axios parameter creator
 */
export const DeleteApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Удаляет пещеру по идентификатору. Если пещера используется — вернёт 400.
         * @summary Удалить пещеру
         * @param {number} id ID пещеры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCaveById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteCaveById', 'id', id)
            const localVarPath = `/deleteCaveById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Удаляет координаты по идентификатору. Если координаты используются — вернёт 400.
         * @summary Удалить координаты
         * @param {number} id ID координат
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCoordinatesById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteCoordinatesById', 'id', id)
            const localVarPath = `/deleteCoordinatesById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Удаляет голову по идентификатору. Если используется — вернёт 400.
         * @summary Удалить голову дракона
         * @param {number} id ID головы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteHeadById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteHeadById', 'id', id)
            const localVarPath = `/deleteHeadById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Удаляет локацию по идентификатору. Если используется — вернёт 400.
         * @summary Удалить локацию
         * @param {number} id ID локации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLocationById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteLocationById', 'id', id)
            const localVarPath = `/deleteLocationById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Удаляет персонажа по идентификатору. Если используется как убийца — вернёт 400.
         * @summary Удалить персонажа
         * @param {number} id ID персонажа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePersonById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePersonById', 'id', id)
            const localVarPath = `/deletePersonById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeleteApi - functional programming interface
 */
export const DeleteApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DeleteApiAxiosParamCreator(configuration)
    return {
        /**
         * Удаляет пещеру по идентификатору. Если пещера используется — вернёт 400.
         * @summary Удалить пещеру
         * @param {number} id ID пещеры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCaveById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCaveById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeleteApi.deleteCaveById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Удаляет координаты по идентификатору. Если координаты используются — вернёт 400.
         * @summary Удалить координаты
         * @param {number} id ID координат
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCoordinatesById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCoordinatesById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeleteApi.deleteCoordinatesById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Удаляет голову по идентификатору. Если используется — вернёт 400.
         * @summary Удалить голову дракона
         * @param {number} id ID головы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteHeadById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteHeadById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeleteApi.deleteHeadById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Удаляет локацию по идентификатору. Если используется — вернёт 400.
         * @summary Удалить локацию
         * @param {number} id ID локации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteLocationById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteLocationById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeleteApi.deleteLocationById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Удаляет персонажа по идентификатору. Если используется как убийца — вернёт 400.
         * @summary Удалить персонажа
         * @param {number} id ID персонажа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePersonById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePersonById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeleteApi.deletePersonById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DeleteApi - factory interface
 */
export const DeleteApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DeleteApiFp(configuration)
    return {
        /**
         * Удаляет пещеру по идентификатору. Если пещера используется — вернёт 400.
         * @summary Удалить пещеру
         * @param {number} id ID пещеры
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCaveById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.deleteCaveById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Удаляет координаты по идентификатору. Если координаты используются — вернёт 400.
         * @summary Удалить координаты
         * @param {number} id ID координат
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCoordinatesById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.deleteCoordinatesById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Удаляет голову по идентификатору. Если используется — вернёт 400.
         * @summary Удалить голову дракона
         * @param {number} id ID головы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteHeadById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.deleteHeadById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Удаляет локацию по идентификатору. Если используется — вернёт 400.
         * @summary Удалить локацию
         * @param {number} id ID локации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLocationById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.deleteLocationById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Удаляет персонажа по идентификатору. Если используется как убийца — вернёт 400.
         * @summary Удалить персонажа
         * @param {number} id ID персонажа
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePersonById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.deletePersonById(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeleteApi - object-oriented interface
 */
export class DeleteApi extends BaseAPI {
    /**
     * Удаляет пещеру по идентификатору. Если пещера используется — вернёт 400.
     * @summary Удалить пещеру
     * @param {number} id ID пещеры
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCaveById(id: number, options?: RawAxiosRequestConfig) {
        return DeleteApiFp(this.configuration).deleteCaveById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Удаляет координаты по идентификатору. Если координаты используются — вернёт 400.
     * @summary Удалить координаты
     * @param {number} id ID координат
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCoordinatesById(id: number, options?: RawAxiosRequestConfig) {
        return DeleteApiFp(this.configuration).deleteCoordinatesById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Удаляет голову по идентификатору. Если используется — вернёт 400.
     * @summary Удалить голову дракона
     * @param {number} id ID головы
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteHeadById(id: number, options?: RawAxiosRequestConfig) {
        return DeleteApiFp(this.configuration).deleteHeadById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Удаляет локацию по идентификатору. Если используется — вернёт 400.
     * @summary Удалить локацию
     * @param {number} id ID локации
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteLocationById(id: number, options?: RawAxiosRequestConfig) {
        return DeleteApiFp(this.configuration).deleteLocationById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Удаляет персонажа по идентификатору. Если используется как убийца — вернёт 400.
     * @summary Удалить персонажа
     * @param {number} id ID персонажа
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePersonById(id: number, options?: RawAxiosRequestConfig) {
        return DeleteApiFp(this.configuration).deletePersonById(id, options).then((request) => request(this.axios, this.basePath));
    }
}

