/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Dragon } from '../models';
// @ts-ignore
import type { DragonDTO } from '../models';
// @ts-ignore
import type { NewDragonResp } from '../models';
/**
 * DragonApi - axios parameter creator
 */
export const DragonApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Создаёт дракона на основании составного запроса. Отправляет обновлённый список по WebSocket.
         * @summary Создать дракона
         * @param {NewDragonResp} newDragonResp Данные для создания дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDragon: async (newDragonResp: NewDragonResp, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newDragonResp' is not null or undefined
            assertParamExists('createDragon', 'newDragonResp', newDragonResp)
            const localVarPath = `/createDragon`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newDragonResp, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Удаляет дракона, отправляет обновлённый список по WebSocket.
         * @summary Удалить дракона по ID
         * @param {number} id ID дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDragonById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteDragonById', 'id', id)
            const localVarPath = `/deleteDragonById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает дракона по идентификатору.
         * @summary Получить дракона по ID
         * @param {number} id ID дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDragonById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getDragonById', 'id', id)
            const localVarPath = `/getDragonById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает полный список драконов.
         * @summary Получить всех драконов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDragons: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getDragons`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Обновляет данные дракона и возвращает DTO.
         * @summary Обновить дракона по ID
         * @param {number} id ID дракона
         * @param {Dragon} dragon Обновлённые данные дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDragonById: async (id: number, dragon: Dragon, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateDragonById', 'id', id)
            // verify required parameter 'dragon' is not null or undefined
            assertParamExists('updateDragonById', 'dragon', dragon)
            const localVarPath = `/updateDragonById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dragon, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DragonApi - functional programming interface
 */
export const DragonApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DragonApiAxiosParamCreator(configuration)
    return {
        /**
         * Создаёт дракона на основании составного запроса. Отправляет обновлённый список по WebSocket.
         * @summary Создать дракона
         * @param {NewDragonResp} newDragonResp Данные для создания дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDragon(newDragonResp: NewDragonResp, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDragon(newDragonResp, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DragonApi.createDragon']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Удаляет дракона, отправляет обновлённый список по WebSocket.
         * @summary Удалить дракона по ID
         * @param {number} id ID дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDragonById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDragonById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DragonApi.deleteDragonById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает дракона по идентификатору.
         * @summary Получить дракона по ID
         * @param {number} id ID дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDragonById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Dragon>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDragonById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DragonApi.getDragonById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает полный список драконов.
         * @summary Получить всех драконов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDragons(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Dragon>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDragons(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DragonApi.getDragons']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Обновляет данные дракона и возвращает DTO.
         * @summary Обновить дракона по ID
         * @param {number} id ID дракона
         * @param {Dragon} dragon Обновлённые данные дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDragonById(id: number, dragon: Dragon, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DragonDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDragonById(id, dragon, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DragonApi.updateDragonById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DragonApi - factory interface
 */
export const DragonApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DragonApiFp(configuration)
    return {
        /**
         * Создаёт дракона на основании составного запроса. Отправляет обновлённый список по WebSocket.
         * @summary Создать дракона
         * @param {NewDragonResp} newDragonResp Данные для создания дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDragon(newDragonResp: NewDragonResp, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.createDragon(newDragonResp, options).then((request) => request(axios, basePath));
        },
        /**
         * Удаляет дракона, отправляет обновлённый список по WebSocket.
         * @summary Удалить дракона по ID
         * @param {number} id ID дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDragonById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.deleteDragonById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает дракона по идентификатору.
         * @summary Получить дракона по ID
         * @param {number} id ID дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDragonById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Dragon> {
            return localVarFp.getDragonById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает полный список драконов.
         * @summary Получить всех драконов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDragons(options?: RawAxiosRequestConfig): AxiosPromise<Array<Dragon>> {
            return localVarFp.getDragons(options).then((request) => request(axios, basePath));
        },
        /**
         * Обновляет данные дракона и возвращает DTO.
         * @summary Обновить дракона по ID
         * @param {number} id ID дракона
         * @param {Dragon} dragon Обновлённые данные дракона
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDragonById(id: number, dragon: Dragon, options?: RawAxiosRequestConfig): AxiosPromise<DragonDTO> {
            return localVarFp.updateDragonById(id, dragon, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DragonApi - object-oriented interface
 */
export class DragonApi extends BaseAPI {
    /**
     * Создаёт дракона на основании составного запроса. Отправляет обновлённый список по WebSocket.
     * @summary Создать дракона
     * @param {NewDragonResp} newDragonResp Данные для создания дракона
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDragon(newDragonResp: NewDragonResp, options?: RawAxiosRequestConfig) {
        return DragonApiFp(this.configuration).createDragon(newDragonResp, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Удаляет дракона, отправляет обновлённый список по WebSocket.
     * @summary Удалить дракона по ID
     * @param {number} id ID дракона
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDragonById(id: number, options?: RawAxiosRequestConfig) {
        return DragonApiFp(this.configuration).deleteDragonById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает дракона по идентификатору.
     * @summary Получить дракона по ID
     * @param {number} id ID дракона
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDragonById(id: number, options?: RawAxiosRequestConfig) {
        return DragonApiFp(this.configuration).getDragonById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает полный список драконов.
     * @summary Получить всех драконов
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDragons(options?: RawAxiosRequestConfig) {
        return DragonApiFp(this.configuration).getDragons(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Обновляет данные дракона и возвращает DTO.
     * @summary Обновить дракона по ID
     * @param {number} id ID дракона
     * @param {Dragon} dragon Обновлённые данные дракона
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateDragonById(id: number, dragon: Dragon, options?: RawAxiosRequestConfig) {
        return DragonApiFp(this.configuration).updateDragonById(id, dragon, options).then((request) => request(this.axios, this.basePath));
    }
}

