/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Dragon } from '../models';
// @ts-ignore
import type { DragonDTO } from '../models';
// @ts-ignore
import type { KillDragonDTO } from '../models';
/**
 * SpecialApi - axios parameter creator
 */
export const SpecialApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Средний возраст драконов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAvgAge: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dragons/avgAge`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ищет дракона, у которого размер головы больше указанного параметра.
         * @summary Дракон с головой больше параметра
         * @param {number} param Пороговое значение для размера головы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDragonHeadGreater: async (param: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'param' is not null or undefined
            assertParamExists('getDragonHeadGreater', 'param', param)
            const localVarPath = `/dragons/headGreater/{param}`
                .replace(`{${"param"}}`, encodeURIComponent(String(param)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Дракон с максимальной пещерой
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDragonWithMaxCave: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dragons/maxCave`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Самый старый дракон
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOldestDragon: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dragons/oldest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Отмечает дракона как убитого, связывая с указанным убийцей. 404 — если дракон/убийца не найдены, 409 — если уже убит.
         * @summary Убить дракона
         * @param {KillDragonDTO} killDragonDTO ID дракона и убийцы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        killDragon: async (killDragonDTO: KillDragonDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'killDragonDTO' is not null or undefined
            assertParamExists('killDragon', 'killDragonDTO', killDragonDTO)
            const localVarPath = `/dragons/kill`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(killDragonDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpecialApi - functional programming interface
 */
export const SpecialApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SpecialApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Средний возраст драконов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAvgAge(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAvgAge(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpecialApi.getAvgAge']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ищет дракона, у которого размер головы больше указанного параметра.
         * @summary Дракон с головой больше параметра
         * @param {number} param Пороговое значение для размера головы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDragonHeadGreater(param: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DragonDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDragonHeadGreater(param, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpecialApi.getDragonHeadGreater']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Дракон с максимальной пещерой
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDragonWithMaxCave(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DragonDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDragonWithMaxCave(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpecialApi.getDragonWithMaxCave']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Самый старый дракон
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOldestDragon(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DragonDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOldestDragon(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpecialApi.getOldestDragon']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Отмечает дракона как убитого, связывая с указанным убийцей. 404 — если дракон/убийца не найдены, 409 — если уже убит.
         * @summary Убить дракона
         * @param {KillDragonDTO} killDragonDTO ID дракона и убийцы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async killDragon(killDragonDTO: KillDragonDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Dragon>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.killDragon(killDragonDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpecialApi.killDragon']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SpecialApi - factory interface
 */
export const SpecialApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SpecialApiFp(configuration)
    return {
        /**
         *
         * @summary Средний возраст драконов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAvgAge(options?: RawAxiosRequestConfig): AxiosPromise<number> {
            return localVarFp.getAvgAge(options).then((request) => request(axios, basePath));
        },
        /**
         * Ищет дракона, у которого размер головы больше указанного параметра.
         * @summary Дракон с головой больше параметра
         * @param {number} param Пороговое значение для размера головы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDragonHeadGreater(param: number, options?: RawAxiosRequestConfig): AxiosPromise<DragonDTO> {
            return localVarFp.getDragonHeadGreater(param, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Дракон с максимальной пещерой
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDragonWithMaxCave(options?: RawAxiosRequestConfig): AxiosPromise<DragonDTO> {
            return localVarFp.getDragonWithMaxCave(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Самый старый дракон
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOldestDragon(options?: RawAxiosRequestConfig): AxiosPromise<DragonDTO> {
            return localVarFp.getOldestDragon(options).then((request) => request(axios, basePath));
        },
        /**
         * Отмечает дракона как убитого, связывая с указанным убийцей. 404 — если дракон/убийца не найдены, 409 — если уже убит.
         * @summary Убить дракона
         * @param {KillDragonDTO} killDragonDTO ID дракона и убийцы
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        killDragon(killDragonDTO: KillDragonDTO, options?: RawAxiosRequestConfig): AxiosPromise<Dragon> {
            return localVarFp.killDragon(killDragonDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SpecialApi - object-oriented interface
 */
export class SpecialApi extends BaseAPI {
    /**
     *
     * @summary Средний возраст драконов
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAvgAge(options?: RawAxiosRequestConfig) {
        return SpecialApiFp(this.configuration).getAvgAge(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ищет дракона, у которого размер головы больше указанного параметра.
     * @summary Дракон с головой больше параметра
     * @param {number} param Пороговое значение для размера головы
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDragonHeadGreater(param: number, options?: RawAxiosRequestConfig) {
        return SpecialApiFp(this.configuration).getDragonHeadGreater(param, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Дракон с максимальной пещерой
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDragonWithMaxCave(options?: RawAxiosRequestConfig) {
        return SpecialApiFp(this.configuration).getDragonWithMaxCave(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Самый старый дракон
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOldestDragon(options?: RawAxiosRequestConfig) {
        return SpecialApiFp(this.configuration).getOldestDragon(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Отмечает дракона как убитого, связывая с указанным убийцей. 404 — если дракон/убийца не найдены, 409 — если уже убит.
     * @summary Убить дракона
     * @param {KillDragonDTO} killDragonDTO ID дракона и убийцы
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public killDragon(killDragonDTO: KillDragonDTO, options?: RawAxiosRequestConfig) {
        return SpecialApiFp(this.configuration).killDragon(killDragonDTO, options).then((request) => request(this.axios, this.basePath));
    }
}

