
CREATE TABLE dragons
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    coordinates_id BIGINT                                  NOT NULL,
    creation_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    cave_id        BIGINT                                  NOT NULL,
    killer_id      BIGINT,
    age            BIGINT                                  NOT NULL,
    description    VARCHAR(255)                            NOT NULL,
    wingspan       FLOAT,
    type           VARCHAR(255),
    head_id        BIGINT,
    CONSTRAINT pk_dragons PRIMARY KEY (id)
);

ALTER TABLE dragons
    ADD CONSTRAINT uc_dragons_name UNIQUE (name);

ALTER TABLE dragons
    ADD CONSTRAINT FK_DRAGON_CAVE FOREIGN KEY (cave_id) REFERENCES dragon_caves (id);

ALTER TABLE dragons
    ADD CONSTRAINT FK_DRAGON_COORDINATES FOREIGN KEY (coordinates_id) REFERENCES coordinates (id);

ALTER TABLE dragons
    ADD CONSTRAINT FK_DRAGON_HEAD FOREIGN KEY (head_id) REFERENCES dragon_heads (id);

ALTER TABLE dragons
    ADD CONSTRAINT FK_DRAGON_KILLER FOREIGN KEY (killer_id) REFERENCES persons (id);