/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Coordinates } from './coordinates';
// May contain unused imports in some cases
// @ts-ignore
import type { DragonCave } from './dragon-cave';
// May contain unused imports in some cases
// @ts-ignore
import type { DragonHead } from './dragon-head';
// May contain unused imports in some cases
// @ts-ignore
import type { Person } from './person';

/**
 * Запрос на аутентификацию
 */
export interface NewDragonResp {
    'name': string;
    'coordinates': Coordinates;
    'cave': DragonCave;
    'killer'?: Person;
    'age'?: number;
    'description': string;
    'wingspan'?: number;
    'type': NewDragonRespTypeEnum;
    'head'?: DragonHead;
}

export const NewDragonRespTypeEnum = {
    Water: 'WATER',
    Underground: 'UNDERGROUND',
    Air: 'AIR',
    Fire: 'FIRE'
} as const;

export type NewDragonRespTypeEnum = typeof NewDragonRespTypeEnum[keyof typeof NewDragonRespTypeEnum];


