/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Location } from './location';

export interface Person {
    'id'?: number;
    'name': string;
    'eyeColor': PersonEyeColorEnum;
    'hairColor'?: PersonHairColorEnum;
    'location'?: Location;
    'passportID': string;
    'nationality': PersonNationalityEnum;
}

export const PersonEyeColorEnum = {
    Red: 'RED',
    Black: 'BLACK',
    Yellow: 'YELLOW',
    White: 'WHITE',
    Brown: 'BROWN'
} as const;

export type PersonEyeColorEnum = typeof PersonEyeColorEnum[keyof typeof PersonEyeColorEnum];
export const PersonHairColorEnum = {
    Red: 'RED',
    Black: 'BLACK',
    Yellow: 'YELLOW',
    White: 'WHITE',
    Brown: 'BROWN'
} as const;

export type PersonHairColorEnum = typeof PersonHairColorEnum[keyof typeof PersonHairColorEnum];
export const PersonNationalityEnum = {
    France: 'FRANCE',
    Spain: 'SPAIN',
    Vatican: 'VATICAN',
    Italy: 'ITALY',
    NorthKorea: 'NORTH_KOREA'
} as const;

export type PersonNationalityEnum = typeof PersonNationalityEnum[keyof typeof PersonNationalityEnum];


