/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationDTO } from './location-dto';

export interface PersonDTO {
    'id'?: number;
    'name'?: string;
    'eyeColor'?: PersonDTOEyeColorEnum;
    'hairColor'?: PersonDTOHairColorEnum;
    'passportID'?: string;
    'nationality'?: PersonDTONationalityEnum;
    'location'?: LocationDTO;
}

export const PersonDTOEyeColorEnum = {
    Red: 'RED',
    Black: 'BLACK',
    Yellow: 'YELLOW',
    White: 'WHITE',
    Brown: 'BROWN'
} as const;

export type PersonDTOEyeColorEnum = typeof PersonDTOEyeColorEnum[keyof typeof PersonDTOEyeColorEnum];
export const PersonDTOHairColorEnum = {
    Red: 'RED',
    Black: 'BLACK',
    Yellow: 'YELLOW',
    White: 'WHITE',
    Brown: 'BROWN'
} as const;

export type PersonDTOHairColorEnum = typeof PersonDTOHairColorEnum[keyof typeof PersonDTOHairColorEnum];
export const PersonDTONationalityEnum = {
    France: 'FRANCE',
    Spain: 'SPAIN',
    Vatican: 'VATICAN',
    Italy: 'ITALY',
    NorthKorea: 'NORTH_KOREA'
} as const;

export type PersonDTONationalityEnum = typeof PersonDTONationalityEnum[keyof typeof PersonDTONationalityEnum];


