
CREATE TABLE persons
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    eye_color   VARCHAR(255)                            NOT NULL,
    hair_color  VARCHAR(255),
    location_id BIGINT,
    passportid  VARCHAR(255)                            NOT NULL,
    nationality VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

ALTER TABLE persons
    ADD CONSTRAINT uc_persons_passportid UNIQUE (passportid);

ALTER TABLE persons
    ADD CONSTRAINT FK_PERSONS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);