CREATE TABLE dragons
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    coordinates_id BIGINT                                  NOT NULL,
    creation_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    cave_id        BIGINT                                  NOT NULL,
    killer_id      BIGINT,
    age            BIGINT                                  NOT NULL,
    description    VARCHAR(255)                            NOT NULL,
    wingspan       FLOAT,
    type           VARCHAR(255),
    head_id        BIGINT,
    CONSTRAINT pk_dragons PRIMARY KEY (id),
    CONSTRAINT uc_dragons_name UNIQUE (name)
);

