CREATE TABLE dragon_heads
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    size        BIGINT                                  NOT NULL,
    eyes_count  INTEGER                                 NOT NULL,
    tooth_count INTEGER                                 NOT NULL,
    CONSTRAINT pk_dragon_heads PRIMARY KEY (id)
);