

CREATE TABLE IF NOT EXISTS operation_history
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_owner BIGINT NOT NULL,
    added_objects   BIGINT,
    creation_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);




DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM   information_schema.table_constraints tc
            WHERE  tc.constraint_schema = current_schema()
              AND  tc.table_name = 'operation_history'
              AND  tc.constraint_type = 'FOREIGN KEY'
              AND  tc.constraint_name = 'fk_operation_history_owner'
        ) THEN
            ALTER TABLE operation_history
                ADD CONSTRAINT fk_operation_history_owner
                    FOREIGN KEY (operation_owner)
                        REFERENCES users (id)
                        ON UPDATE RESTRICT
                        ON DELETE RESTRICT;

        END IF;
    END $$;
