
CREATE TABLE operation_history
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    operation_owner BIGINT                                  NOT NULL,
    added_objects   BIGINT,
    creation_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_operation_history PRIMARY KEY (id)
);

ALTER TABLE operation_history
    ADD CONSTRAINT FK_OWNER FOREIGN KEY (operation_owner) REFERENCES users (id);