CREATE TABLE locations
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x    FLOAT                                   NOT NULL,
    y    FLOAT                                   NOT NULL,
    z    INTEGER                                 NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_locations PRIMARY KEY (id)
);