CREATE TABLE coordinates
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x  FLOAT                                   NOT NULL,
    y  DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_coordinates PRIMARY KEY (id)
);